-- ==========================================
-- Supabase Database Schema Setup
-- ==========================================

-- Enable the http extension for fetching remote images (if needed in future)
create extension if not exists http;

-- ==========================================
-- Storage: Create bucket for product images
-- ==========================================

-- Create a bucket for product images
insert into storage.buckets (id, name, public)
values ('product_images', 'product_images', true)
on conflict (id) do nothing;

-- Set up storage policies for product_images bucket
-- Allow public read access
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'product_images' );

-- Allow authenticated users to upload
create policy "Authenticated users can upload"
on storage.objects for insert
with check ( bucket_id = 'product_images' );

-- Allow authenticated users to update their uploads
create policy "Authenticated users can update"
on storage.objects for update
using ( bucket_id = 'product_images' );

-- Allow authenticated users to delete their uploads
create policy "Authenticated users can delete"
on storage.objects for delete
using ( bucket_id = 'product_images' );

-- ==========================================
-- Table: Products
-- ==========================================

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,

  -- Add constraints
  constraint products_name_not_empty check (length(trim(name)) > 0)
);

-- Add index for faster queries
create index if not exists products_created_at_idx on public.products(created_at desc);
create index if not exists products_name_idx on public.products(name);

-- Enable Row Level Security
alter table public.products enable row level security;

-- Create policies for products table
create policy "Enable read access for all users"
on public.products for select
using (true);

create policy "Enable insert for authenticated users only"
on public.products for insert
with check (true);

create policy "Enable update for authenticated users only"
on public.products for update
using (true);

-- ==========================================
-- Table: Orders
-- ==========================================

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  order_number text not null unique,
  customer_email text not null,
  status text not null default 'pending',
  tracking_number text,

  -- Add constraints
  constraint orders_order_number_not_empty check (length(trim(order_number)) > 0),
  constraint orders_customer_email_valid check (customer_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'),
  constraint orders_status_not_empty check (length(trim(status)) > 0)
);

-- Add indexes for faster queries
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_order_number_idx on public.orders(order_number);
create index if not exists orders_customer_email_idx on public.orders(customer_email);
create index if not exists orders_status_idx on public.orders(status);

-- Enable Row Level Security
alter table public.orders enable row level security;

-- Create policies for orders table
create policy "Enable read access for all users"
on public.orders for select
using (true);

create policy "Enable insert for authenticated users only"
on public.orders for insert
with check (true);

create policy "Enable update for authenticated users only"
on public.orders for update
using (true);

-- ==========================================
-- Sample Data (Optional - for testing)
-- ==========================================

-- Insert sample orders for testing
insert into public.orders (order_number, customer_email, status, tracking_number)
values
  ('123', 'customer1@example.com', 'pending', null),
  ('456', 'customer2@example.com', 'processing', null),
  ('789', 'customer3@example.com', 'shipped', '1Z999AA10123456784')
on conflict (order_number) do nothing;

-- ==========================================
-- Comments for documentation
-- ==========================================

comment on table public.products is 'Stores product information including name, price, description, and image URL';
comment on table public.orders is 'Stores order information including order number, customer email, status, and tracking number';

comment on column public.products.id is 'Unique identifier for the product';
comment on column public.products.created_at is 'Timestamp when the product was created';
comment on column public.products.name is 'Name of the product';
comment on column public.products.description is 'Detailed description of the product';
comment on column public.products.price is 'Price of the product in USD';
comment on column public.products.image_url is 'Public URL of the product image stored in Supabase Storage';

comment on column public.orders.id is 'Unique identifier for the order';
comment on column public.orders.created_at is 'Timestamp when the order was created';
comment on column public.orders.order_number is 'Unique order number for tracking';
comment on column public.orders.customer_email is 'Email address of the customer';
comment on column public.orders.status is 'Current status of the order (e.g., pending, shipped, delivered)';
comment on column public.orders.tracking_number is 'Shipping tracking number (optional)';
